export const ACTIONS = {
    AUTH: {
        LOGIN_FETCHING: 'LOGIN_FETCHING',
        LOGIN_RECEIVED: 'LOGIN_RECEIVED',
        LOGIN_REJECTED: 'LOGIN_REJECTED',
        LOGIN_INVALIDATED: 'LOGIN_INVALIDATED',
        CURRENT_USER_FETCHING: 'CURRENT_USER_FETCHING',
        CURRENT_USER_RECEIVED: 'CURRENT_USER_RECEIVED',
        CURRENT_USER_REJECTED: 'CURRENT_USER_REJECTED',
    },
    DICTA: {
        FETCH_REQUEST: 'DICTA_FETCH_REQUEST',
        FETCH_RECEIVED: 'DICTA_FETCH_RECEIVED',
        FETCH_REJECTED: 'DICTA_FETCH_REJECTED',
        CREATE_REQUEST: 'DICTA_CREATE_REQUEST',
        CREATE_RECEIVED: 'DICTA_CREATE_RECEIVED',
        CREATE_REJECTED: 'DICTA_CREATE_REJECTED',
        CREATE_INVALIDATED: 'DICTA_CREATE_INVALIDATED',
    }
}