export const ACTIONS = {
    AUTH: {
        CURRENT_USER_FETCHING: 'CURRENT_USER_FETCHING',
        CURRENT_USER_RECEIVED: 'CURRENT_USER_RECEIVED',
        CURRENT_USER_REJECTED: 'CURRENT_USER_REJECTED',
    },
    DICTA: {
        REQUESTING: 'DICTA_REQUESTING',
        RECEIVED: 'DICTA_RECEIVED',
        REJECTED: 'DICTA_REJECTED',
    }
}